export const stallRecoveryJudokaFixtures = [
  {
    id: 1,
    firstname: "Test",
    surname: "Player",
    country: "United States",
    countryCode: "us",
    weightClass: "-81",
    category: "Judo",
    stats: { power: 5, speed: 5, technique: 5, kumikata: 5, newaza: 5 },
    signatureMoveId: 0,
    lastUpdated: "2025-01-01T00:00:00.000Z",
    profileUrl: "",
    bio: "Test player for stall recovery tests",
    gender: "male",
    isHidden: false,
    rarity: "Common",
    cardCode: "TEST-PLYR-0001",
    matchesWon: 0,
    matchesLost: 0,
    matchesDrawn: 0
  },
  {
    id: 2,
    firstname: "Test",
    surname: "Opponent",
    country: "Japan",
    countryCode: "jp",
    weightClass: "-81",
    category: "Judo",
    stats: { power: 3, speed: 3, technique: 3, kumikata: 3, newaza: 3 },
    signatureMoveId: 0,
    lastUpdated: "2025-01-01T00:00:00.000Z",
    profileUrl: "",
    bio: "Test opponent for stall recovery tests",
    gender: "male",
    isHidden: false,
    rarity: "Common",
    cardCode: "TEST-OPNT-0002",
    matchesWon: 0,
    matchesLost: 0,
    matchesDrawn: 0
  }
];
