name: Build Offline RAG (Manual)

on:
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: "Ignore drift and rebuild anyway"
        required: false
        default: "false"

permissions:
  contents: write
  pull-requests: write

jobs:
  build_offline_rag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

            # Optional: try a drift check; if checker is missing OR force_rebuild=true, mark stale
      - name: (Optional) Check offline RAG drift
        id: drift
        shell: bash
        run: |
          set +e
          STALE="true"  # default to stale if checker missing
          if npm run -s check:offline-rag >/dev/null 2>&1; then
            npm run -s check:offline-rag
            CODE=$?
            if [ $CODE -eq 0 ]; then STALE="false"; fi
          fi
          if [ "${{ github.event.inputs.force_rebuild }}" = "true" ]; then
            STALE="true"
          fi
          echo "stale=$STALE" >> $GITHUB_OUTPUT
          echo "DRIFT stale? $STALE"

      - name: Prepare output folder
        if: steps.drift.outputs.stale == 'true'
        run: mkdir -p src/rag-offline

      - name: Build offline index (debug)
        if: steps.drift.outputs.stale == 'true'
        env:
          TRANSFORMERS_OFFLINE: "1"
          HF_HUB_OFFLINE: "1"
          NODE_OPTIONS: "--experimental-json-modules"
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p src/rag-offline

          # Prefer explicit outputs if your script supports flags
          if node scripts/buildOfflineRag.mjs --help >/dev/null 2>&1; then
            node scripts/buildOfflineRag.mjs \
              --out  src/rag-offline/offline.index.json \
              --meta src/rag-offline/offline.index.meta.json
          else
            npm run build:offline-rag
          fi

          echo '--- after-build tree (src/rag-offline) ---'
          (cd src && find rag-offline -maxdepth 2 -type f -print 2>/dev/null || true)
          echo '--- recent files anywhere under src (matching "offline") ---'
          (cd src && find . -type f -iname '*offline*' -print 2>/dev/null || true)


      - name: Assert expected files exist (fail fast if missing)
        if: steps.drift.outputs.stale == 'true'
        shell: bash
        run: |
          err=0
          test -f src/rag-offline/offline.index.json || { echo "❌ missing offline.index.json"; err=1; }
          test -f src/rag-offline/offline.index.meta.json || { echo "❌ missing offline.index.meta.json"; err=1; }
          if [ $err -ne 0 ]; then
            echo "Hint: verify buildOfflineRag.mjs writes to src/rag-offline/ or add --out/--meta flags."
            exit 1
          fi

      # Quick check: show sizes, hashes, and meta so logs prove state
      - name: Quick check of offline artifacts
        shell: bash
        run: |
          echo "=== Current offline artifacts ==="
          for f in src/rag-offline/offline.index.json src/rag-offline/offline.index.meta.json; do
            if [ -f "$f" ]; then
              echo "File: $f"
              wc -c "$f"
              sha256sum "$f" || true
            else
              echo "MISSING: $f"
            fi
          done
          echo "--- tree (rag-offline) ---"
          (cd src && find rag-offline -maxdepth 2 -type f -print 2>/dev/null || true)
          echo "--- meta ---"
          if [ -f src/rag-offline/offline.index.meta.json ]; then
            jq -r '.buildHash, "docs=\(.counts.docs) dim=\(.counts.dim) createdAt=\(.createdAt)"' src/rag-offline/offline.index.meta.json
          fi


      - name: Stage changes
        id: stage
        shell: bash
        run: |
          # Add typical offline outputs; ignore if absent
          git add src/rag-offline/offline.index.json 2>/dev/null || true
          git add src/rag-offline/offline.index.meta.json 2>/dev/null || true
          git add src/rag-offline/offline.bm25.json 2>/dev/null || true
          git add src/rag-offline/offline.index.starter.json 2>/dev/null || true

          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Summarize sizes
        if: steps.stage.outputs.changed == 'true'
        id: sizes
        shell: bash
        run: |
          size_kb () { test -f "$1" && echo "$(($(wc -c < "$1")/1024))KB" || echo "—"; }
          IDX_SZ=$(size_kb src/rag-offline/offline.index.json)
          BM25_SZ=$(size_kb src/rag-offline/offline.bm25.json)
          META_SZ=$(size_kb src/rag-offline/offline.index.meta.json)

          if [ -f src/rag-offline/offline.index.meta.json ]; then
            DOCS=$(jq -r '.counts.docs // .count // "?"' src/rag-offline/offline.index.meta.json)
            DIM=$(jq -r '.counts.dim // "?"' src/rag-offline/offline.index.meta.json)
          else
            DOCS="?"
            DIM="?"
          fi

          echo "idx=${IDX_SZ}"  >> $GITHUB_OUTPUT
          echo "bm25=${BM25_SZ}" >> $GITHUB_OUTPUT
          echo "meta=${META_SZ}" >> $GITHUB_OUTPUT
          echo "docs=${DOCS}"    >> $GITHUB_OUTPUT
          echo "dim=${DIM}"      >> $GITHUB_OUTPUT

          {
            echo "### Offline RAG Build Summary"
            echo ""
            echo "- **Index size:** ${IDX_SZ}"
            echo "- **BM25 size:** ${BM25_SZ}"
            echo "- **Meta size:** ${META_SZ}"
            echo "- **Docs:** ${DOCS}"
            echo "- **Dim:** ${DIM}"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Create Pull Request
        if: steps.stage.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(rag-offline): refresh offline RAG index"
          title: "Offline RAG refresh ($(date +'%Y-%m-%d'))"
          body: |
            This PR refreshes the **offline RAG** artifacts.

            **Summary**
            - Index size: ${{ steps.sizes.outputs.idx }}
            - BM25 size:  ${{ steps.sizes.outputs.bm25 }}
            - Meta size:  ${{ steps.sizes.outputs.meta }}
            - Docs:       ${{ steps.sizes.outputs.docs }}
            - Dim:        ${{ steps.sizes.outputs.dim }}

            Notes:
            - Build forced offline: `TRANSFORMERS_OFFLINE=1`, `HF_HUB_OFFLINE=1`
            - Uses script: `npm run build:offline-rag`
          branch: chore/offline-rag-refresh
          labels: |
            automated
            offline
            vector

      - name: No changes
        if: steps.stage.outputs.changed != 'true'
        run: echo "No offline RAG changes detected."
