name: Prettier Auto-Format

on:
  schedule:
    - cron: "0 3 * * *" # Runs at 3:00 AM UTC every day
  workflow_dispatch: # Allows manual triggering too

permissions:
  contents: write

jobs:
  format:
    name: Run Prettier and Commit Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier . --write

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || (git commit -m "chore: auto-format with Prettier" && git push)
