name: Super-Linter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🧹 Run Super-Linter
        uses: github/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Only enable the linters you want:
          ENABLE_JSCPD: false
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_MARKDOWN: true
          VALIDATE_JSON: false
          VALIDATE_YAML: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_DOCKERFILE: false
